Create setup script
HackGT/api pull request #170
Opened 2023-08-05 01:58 UTC by ayush-goyal

### Description
- Create an interactive setup script for new members to get setup in the api repo
- Checks that they have the proper `.env` file and google cloud secrets
- Ensures the databases are running locally and that migrations are run
- Ensures that their permission and profile is setup locally

Sample screenshot from the script execution
<img width="1112" alt="Screenshot 2023-08-04 at 9 58 04 PM" src="https://github.com/HackGT/api/assets/8273038/bf8ce405-e48e-4ec3-887a-0a147d29ec99">

### Issues

- Closes #158

2023-08-05 23:46 UTC, thaneesh-babu reviewed
Great work! Commented a small thing and would like @Roshan-D to look at this as well since my postgres setup is still iffy

2023-08-05 23:46 UTC, thaneesh-babu commented on scripts/src/setup.ts
> +
can we log a successful mongodb connection message here before checking the postgres setup

2023-08-06 04:39 UTC, thaneesh-babu requested changes
Nvm got postgres working. So it worked well but I had a few other suggestions:
- If you select no for any of the inputs it still continues so I'd guess we wanna exit the script in that case
- For some of the questions like enter uid, name etc, it would be better if we loop for a valid input in case of input invalidation just so that we don't have to restart the script. Something like this:

```
let userId = "";
  while (1) {
    userId = await input({
      message: chalk.cyan("What is your ") + chalk.gray("uid") + chalk.cyan("?: "),
    });
    if (userId.length < 10) {
      logError("Invalid uid. Please ensure you have copied the correct uid.");
      continue;
    }
    break;
  }
```

Everything else is dope!

2023-08-06 17:52 UTC, ayush-goyal commented
Fixed @thaneesh-babu

2023-08-06 20:13 UTC, thaneesh-babu approved these changes
approved if u can just resolve conflicts and then merge

2023-08-06 20:19 UTC, ayush-goyal commented
@Roshan-D if u wanna take a look too lmk

2023-08-07 04:32 UTC, Roshan-D approved these changes
this is amazing! love it!

2023-08-07 06:29 UTC, merged