Migrate team to hexathons
HackGT/api pull request #180
Opened 2023-08-15 20:33 UTC by Roshan-D

### Description
Moved `/team` routes and `Team` modal from the `users` service to the `hexathons` service

### Issues
Addresses #179 
-

2023-08-16 00:32 UTC, amtang325 reviewed
looks good!

2023-08-16 00:36 UTC, ayush-goyal requested changes
A few things, this is gonna break the registration team flow so make sure that’s fixed before you merge this in. Also, you gotta update the model for HexathonUser. Do you have plans to migrate the existing data in the database as well to support this.

2023-08-16 01:36 UTC, thaneesh-babu commented
yeah like ayush said, registration should now interact with the hexathons service for team management stuff

2023-08-23 19:58 UTC, thaneesh-babu requested changes

2023-08-23 19:58 UTC, thaneesh-babu commented on services/hexathons/src/routes/team.ts
>        },
change this term to `hexathonUsers` and the find call should match the hexathon as well, rn hexathon users from all hexathons are taken as valid profiles

2023-08-25 22:55 UTC, merged